# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev7+g1eb4842.d20230523'
__version_tuple__ = version_tuple = (0, 1, 'dev7', 'g1eb4842.d20230523')
