# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.1b1.dev61+g698ae5e.d20230816'
__version_tuple__ = version_tuple = (1, 0, 1, 'dev61', 'g698ae5e.d20230816')
