# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev6+g6ceaccf.d20230523'
__version_tuple__ = version_tuple = (0, 1, 'dev6', 'g6ceaccf.d20230523')
