# Generated by Django 3.2.19 on 2023-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qdjango', '0107_auto_20230516_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='QProcessingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='qprocessing', verbose_name='QGIS processing model file (.model3)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('projects', models.ManyToManyField(to='qdjango.Project')),
            ],
        ),
    ]
