# Generated by Django 3.2.19 on 2023-06-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdjango', '0107_auto_20230516_0806'),
        ('qprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qprocessingproject',
            options={'permissions': (('run_model', 'Can run a QGIS processing model'),)},
        ),
        migrations.AlterField(
            model_name='qprocessingproject',
            name='projects',
            field=models.ManyToManyField(help_text='Select one of more projects to link to this QGIS processing model', to='qdjango.Project'),
        ),
    ]
