# Generated by Django 3.2.20 on 2023-08-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qprocessing', '0003_qprocessinginputupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='qprocessinginputupload',
            name='input_name',
            field=models.CharField(max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qprocessinginputupload',
            name='qpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qprocessing.qprocessingproject'),
            preserve_default=False,
        ),
    ]
