name: QProcessing CI tests

on: [push, pull_request]

jobs:

  ci_tests:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
      with:
        repository: 'g3w-suite/g3w-admin'

    - uses: actions/checkout@v4
      with:
        path: 'qprocessing'

    - name: Move qprocessing inside g3w-admin
      run: mv qprocessing/qprocessing g3w-admin/

    - name: Starting Docker compose
      run: docker compose -f docker-compose.ltr.yml up -d


    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
