name: QProcessing CI tests

on: [push, pull_request]

jobs:

  ci_tests:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
      with:
        repository: 'g3w-suite/g3w-admin'

    - uses: actions/checkout@v4
      with:
        path: 'qprocessing'

    - name: Move qprocessing inside g3w-admin
      run: mv qprocessing/qprocessing g3w-admin/ && echo "$(ls -lh g3w-admin/qprocessing)"

    - name: Starting Docker compose
      run: docker compose -f docker-compose.ltr.yml up -d

    - name: Copying code into the container
      run: |
        docker cp ./ "$(docker compose -f docker-compose.ltr.yml ps -q g3w-suite)":/code

    - name: Installing G3W-ADMIN Python requirements
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "cd /code/ && pip3 install -r requirements_docker.txt"

    - name: Check for QProcessing requirements file
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "cd /code/g3w-admin/qprocessing && ls -lh"

    - name: Installing QProcessing Python requirements
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "cd /code/g3w-admin/qprocessing && pip3 install -r requirements.txt"

    - name: Building g3w-suite
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "/code/ci_scripts/build_suite.sh"

    - name: Setting up g3w-suite
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "/code/ci_scripts/setup_suite.sh"

    - name: Starting Django
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py runserver 0.0.0.0:8000" &

    - name: Waiting for Django
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "wait-for-it -h localhost -p 8000 -t 240"

    - name:  Running QProcessing tests
      run: |
        docker compose -f docker-compose.ltr.yml exec -T g3w-suite sh -c "cd /code/g3w-admin && python3 manage.py test qprocessing"

    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
