name: QProcessing CI tests

on: [push, pull_request]

jobs:

  ci_tests:

    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
      with:
        repository: 'g3w-suite/g3w-suite-docker'
        set-safe-directory: '/home/runner/work/g3w-admin-processing/g3w-suite-docker'

    - name: Extract branch name
      shell: bash
      run: echo "$(ls /home/runner/work/g3w-admin-processing/g3w-suite-docker)"
      id: extract_branch


    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
